// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go_auth-project/api/controller"
	"go_auth-project/api/repository"
	"go_auth-project/api/service"
	"go_auth-project/config"
)

// Injectors from injector.go:

func InitializeAuthController() *controller.AuthController {
	db := config.DatabaseConnection()
	usersRepository := repository.NewUsersREpositoryImpl(db)
	validate := config.NewValidator()
	usersService := service.NewUserServiceImpl(usersRepository, validate)
	authService := service.NewAuthService(usersService)
	AuthController := controller.NewAuthController(usersService, authService)
	return AuthController
}
