// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go-auth/api/controller"
	"go-auth/api/repository"
	"go-auth/api/service"
	"go-auth/config"
)

// Injectors from injector.go:

func AuthInjector() *controller.AuthController {
	db := config.DatabaseConnection()
	usersRepository := repository.NewUsersREpositoryImpl(db)
	validate := config.NewValidator()
	userService := service.NewUserServiceImpl(usersRepository, validate)
	authService := service.NewAuthService(userService)
	authController := controller.NewAuthController(userService, authService)
	return authController
}
